name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # O la rama que estés usando para producción
  pull_request:
    branches:
      - main  # O la rama que estés usando para producción

jobs:
  # Job para ejecutar las pruebas
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia la versión de Node.js según tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

  # Job de deploy (solo se ejecuta en la rama main)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Solo se ejecutará si el job de tests pasa
    if: github.ref == 'refs/heads/main'  # Solo ejecuta este job en la rama main
    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalación de EAS CLI (Expo Application Services)
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 3. Instalación de dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construcción para Android
      - name: Build APK for Android
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Asegúrate de configurar EXPO_TOKEN en GitHub Secrets.

      # 5. Obtener URL del artefacto y subir imagen
      - name: Upload image and send data to API
        run: |
          # Obtener URL del artefacto
          RESPONSE=$(eas build:list --limit=1 --status=finished --json --non-interactive)
          DOWNLOAD_URL=$(echo "$RESPONSE" | jq -r '.[0].artifacts.buildUrl')

          echo "La URL del artefacto obtenida es: $DOWNLOAD_URL"

          # Verificar si la imagen existe
          if [ ! -f "$IMAGE_PATH" ]; then
            echo "La imagen no existe en la ruta especificada: $IMAGE_PATH"
            exit 1
          fi

          # Obtener solo el nombre del archivo desde la ruta completa
          IMAGE_NAME=$(basename "$IMAGE_PATH")
          echo "El nombre del icono es: $IMAGE_NAME"

          # Subir la imagen al servidor PHP
          curl -X POST \
            -F "imagen=@$IMAGE_PATH" \
            "$WEB_SERVICE_URL"

          # Enviar datos a la API de Express
          curl -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "url": "'"$DOWNLOAD_URL"'",
              "nombre": "'"$PROJECT_NAME"'",
              "icono": "'"$IMAGE_NAME"'"
            }'

        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          IMAGE_PATH: ".github/workflows/logoAlev.png"  # Cambia esto a la ruta de tu icono
          WEB_SERVICE_URL: "https://labarbada.store/subirImagen.php"
          API_URL: "https://api-admin-six.vercel.app/api/guardar-datos"  # Cambia por la URL de tu API
          PROJECT_NAME: "Alevosía"  # Cambia este valor por el nombre de tu proyecto
