name: Run React Native Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Configuraci贸n del entorno y chequeo del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuraci贸n de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Instalaci贸n de dependencias
      - name: Install dependencies
        run: npm install

      # Ejecuci贸n de las pruebas
      - name: Run Jest tests
        run: npm test
